# Generated by Django 5.0.4 on 2024-06-02 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diachi',
            fields=[
                ('MaDC', models.AutoField(primary_key=True, serialize=False)),
                ('Duong', models.CharField(max_length=255)),
                ('Tinh', models.CharField(max_length=255)),
                ('Quan', models.CharField(max_length=255)),
                ('Phuong', models.CharField(max_length=255)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
