# Generated by Django 5.0.4 on 2024-06-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_diachi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='DiaChi',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='MaDC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.diachi'),
        ),
    ]
